# Generated by Django 5.0.6 on 2024-06-13 15:55

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер здания')),
                ('corpus', models.CharField(blank=True, max_length=5, null=True, verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новости')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг новости')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент новости')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Опубликована')], verbose_name='Статус новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(verbose_name='Текст заявки')),
                ('status', models.IntegerField(choices=[(1, 'Новая'), (2, 'В работе'), (3, 'Закрыта')], verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка от клиента',
                'verbose_name_plural': 'Заявки от клиентов',
            },
        ),
        migrations.CreateModel(
            name='RequestTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название темы')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тема заявки',
                'verbose_name_plural': 'Темы заявки',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер договора')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.address', verbose_name='Адрес клиента')),
            ],
            options={
                'verbose_name': 'Договор с клиентом',
                'verbose_name_plural': 'Договора с клиентами',
            },
        ),
    ]
